# Generated by Django 5.1.15 on 2026-02-09 11:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='checksum',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='storedfile',
            name='logical_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='storedfile',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
